### ISSUE TITLE
Markdown files support

### ISSUE THREAD

**Issue by VladimirMikulic** [commanditor/app#4]
Hi! This is a really nice and useful editor.
As a developer, I edit a lot of Markdown files, but this editor doesn't support Markdown.

Could you add the support for it?

Thanks.

**Comment by anddam** [comment]
What do you mean? 

I see the manifest specifying .md support and that file has been last updated twelve months ago.

I can open `.md` files from Drive just fine, is that not the case for you?

**Comment by VladimirMikulic** [comment]
Hi @anddam. Sorry for not closing the issue.
I've figured out what my problem was. Google would add its extension to files open in Google Docs so that's why it couldn't open them.
